import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "../globals.css";
import Sidemenu from "@/components/sideMenu/Sidemenu";

const notoSansJp = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "server-remind App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="text-gray-800">
      <body className={notoSansJp.className}>
        <main className="flex">
          <Sidemenu />
          {children}
        </main>
      </body>
    </html>
  );
}
