name: reminder_schedule
on:
  schedule:
    - cron: "0 5 * * *"
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API Endpoint
        run: curl -X POST "${{secrets.API_URL}}/schedule"
